services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - FOREMAN=${FOREMAN:-true}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  db_data:
