FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client imagemagick

RUN gem install bundler -v 2.4.14

WORKDIR /app

COPY . /app/
COPY Gemfile Gemfile.lock ./

RUN bundle install

EXPOSE 3000

CMD bundle exec puma -t 0:5 -p 3000 -e development
